version: '3.8'
services:
  dev-db:
    image: postgis/postgis
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fido
    networks:
      - fidoapp
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

  test-db:
    image: postgis/postgis
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fido
    networks:
      - fidoapp
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      
networks:
  fidoapp: